"""add_historical_match_stats

Revision ID: 3d1e9897ec25
Revises: 603dea087504
Create Date: 2026-05-25 20:14:40.607443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d1e9897ec25'
down_revision: Union[str, None] = '603dea087504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historical_matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stats', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historical_matches', schema=None) as batch_op:
        batch_op.drop_column('stats')

    # ### end Alembic commands ###
