"""initial schema

Revision ID: 603dea087504
Revises: 
Create Date: 2026-05-24 16:17:43.546643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '603dea087504'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_date', sa.Date(), nullable=False),
    sa.Column('home_team', sa.String(), nullable=False),
    sa.Column('away_team', sa.String(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=False),
    sa.Column('away_score', sa.Integer(), nullable=False),
    sa.Column('tournament', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('neutral', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historical_matches', schema=None) as batch_op:
        batch_op.create_index('ix_hist_away', ['away_team'], unique=False)
        batch_op.create_index('ix_hist_date', ['match_date'], unique=False)
        batch_op.create_index('ix_hist_home', ['home_team'], unique=False)

    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('rows_processed', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_versions',
    sa.Column('model_version_id', sa.String(), nullable=False),
    sa.Column('family', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('artifact_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('model_version_id')
    )
    op.create_table('players',
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('position', sa.String(length=4), nullable=True),
    sa.Column('foot', sa.String(length=8), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('nation', sa.String(), nullable=True),
    sa.Column('club', sa.String(), nullable=True),
    sa.Column('league', sa.String(), nullable=True),
    sa.Column('market_value_eur', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('raw_payloads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referees',
    sa.Column('referee_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('avg_yellows', sa.Float(), nullable=True),
    sa.Column('avg_reds', sa.Float(), nullable=True),
    sa.Column('avg_pens', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('referee_id')
    )
    op.create_table('teams',
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('fifa_code', sa.String(length=4), nullable=True),
    sa.Column('confederation', sa.String(), nullable=False),
    sa.Column('fifa_rank', sa.Integer(), nullable=True),
    sa.Column('elo', sa.Float(), nullable=True),
    sa.Column('flag_emoji', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('tournaments',
    sa.Column('tournament_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('host_countries', sa.JSON(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('tournament_id')
    )
    op.create_table('venues',
    sa.Column('venue_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('altitude_m', sa.Integer(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('surface', sa.String(), nullable=True),
    sa.Column('roof', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('venue_id')
    )
    op.create_table('injuries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('reported_at', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expected_return', sa.Date(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('tournament_id', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('group_label', sa.String(length=4), nullable=True),
    sa.Column('match_number', sa.Integer(), nullable=True),
    sa.Column('kickoff_utc', sa.DateTime(), nullable=False),
    sa.Column('venue_id', sa.String(), nullable=True),
    sa.Column('home_team_id', sa.String(), nullable=True),
    sa.Column('away_team_id', sa.String(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('referee_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['referee_id'], ['referees.referee_id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.tournament_id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.venue_id'], ),
    sa.PrimaryKeyConstraint('match_id')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index('ix_matches_kickoff', ['kickoff_utc'], unique=False)
        batch_op.create_index('ix_matches_tournament_stage', ['tournament_id', 'stage'], unique=False)

    op.create_table('player_aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_id')
    )
    op.create_table('simulations',
    sa.Column('simulation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tournament_id', sa.String(), nullable=False),
    sa.Column('model_version_id', sa.String(), nullable=False),
    sa.Column('n_runs', sa.Integer(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('aggregates', sa.JSON(), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('parent_simulation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.model_version_id'], ),
    sa.ForeignKeyConstraint(['parent_simulation_id'], ['simulations.simulation_id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.tournament_id'], ),
    sa.PrimaryKeyConstraint('simulation_id')
    )
    op.create_table('squads',
    sa.Column('squad_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('tournament_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.tournament_id'], ),
    sa.PrimaryKeyConstraint('squad_id')
    )
    op.create_table('team_aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_id')
    )
    op.create_table('counterfactuals',
    sa.Column('scenario_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.simulation_id'], ),
    sa.PrimaryKeyConstraint('scenario_id')
    )
    op.create_table('feature_snapshots',
    sa.Column('snapshot_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('feature_set_version', sa.String(), nullable=False),
    sa.Column('as_of_kickoff', sa.DateTime(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_table('lineups',
    sa.Column('lineup_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('formation', sa.String(length=16), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('lineup_id')
    )
    op.create_table('odds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('bookmaker', sa.String(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('home', sa.Float(), nullable=True),
    sa.Column('draw', sa.Float(), nullable=True),
    sa.Column('away', sa.Float(), nullable=True),
    sa.Column('over_2_5', sa.Float(), nullable=True),
    sa.Column('under_2_5', sa.Float(), nullable=True),
    sa.Column('btts_yes', sa.Float(), nullable=True),
    sa.Column('btts_no', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictions',
    sa.Column('prediction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('model_version_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('p_home', sa.Float(), nullable=True),
    sa.Column('p_draw', sa.Float(), nullable=True),
    sa.Column('p_away', sa.Float(), nullable=True),
    sa.Column('lambda_home', sa.Float(), nullable=True),
    sa.Column('lambda_away', sa.Float(), nullable=True),
    sa.Column('expected_goals_home', sa.Float(), nullable=True),
    sa.Column('expected_goals_away', sa.Float(), nullable=True),
    sa.Column('p_over_2_5', sa.Float(), nullable=True),
    sa.Column('p_btts', sa.Float(), nullable=True),
    sa.Column('scoreline_matrix', sa.JSON(), nullable=True),
    sa.Column('top_factors', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.model_version_id'], ),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index('ix_pred_match_model', ['match_id', 'model_version_id'], unique=False)

    op.create_table('squad_players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('squad_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('shirt_number', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_starter_prob', sa.Float(), nullable=True),
    sa.Column('availability', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.squad_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather_forecasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('temp_c', sa.Float(), nullable=True),
    sa.Column('feels_like_c', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('precipitation_mm', sa.Float(), nullable=True),
    sa.Column('precipitation_prob', sa.Float(), nullable=True),
    sa.Column('wind_kmh', sa.Float(), nullable=True),
    sa.Column('air_quality', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lineup_players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lineup_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('is_starter', sa.Boolean(), nullable=False),
    sa.Column('position', sa.String(length=4), nullable=True),
    sa.ForeignKeyConstraint(['lineup_id'], ['lineups.lineup_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lineup_players')
    op.drop_table('weather_forecasts')
    op.drop_table('squad_players')
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index('ix_pred_match_model')

    op.drop_table('predictions')
    op.drop_table('odds')
    op.drop_table('lineups')
    op.drop_table('feature_snapshots')
    op.drop_table('counterfactuals')
    op.drop_table('team_aliases')
    op.drop_table('squads')
    op.drop_table('simulations')
    op.drop_table('player_aliases')
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index('ix_matches_tournament_stage')
        batch_op.drop_index('ix_matches_kickoff')

    op.drop_table('matches')
    op.drop_table('injuries')
    op.drop_table('venues')
    op.drop_table('tournaments')
    op.drop_table('teams')
    op.drop_table('referees')
    op.drop_table('raw_payloads')
    op.drop_table('players')
    op.drop_table('model_versions')
    op.drop_table('ingestion_runs')
    with op.batch_alter_table('historical_matches', schema=None) as batch_op:
        batch_op.drop_index('ix_hist_home')
        batch_op.drop_index('ix_hist_date')
        batch_op.drop_index('ix_hist_away')

    op.drop_table('historical_matches')
    # ### end Alembic commands ###
